title: "UntangleMyStringArt"
description: "Welcome to Untangle for personalised string art, workshops and parties. You Name it, I NAIL it !! 😃"
baseurl: ""
url: "https://kapricanon.github.io"
theme: jekyll-theme-cayman

include:
- _includes/head-custom.html
- _includes/footer.html




